title = "Outman's Blog"
baseURL = 'https://blog.outmanos.com'

languageCode = 'en-us'

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 20

[params]
  github = "https://github.com/outmanos"
  stackoverflow = "https://stackoverflow.com/users/7026554/outman"
  linkedin = "https://www.linkedin.com/in/outmanos"
  contact = "mailto:outman.blog.contact@gmail.com"
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Related articles"
  favicon = "/favicon.ico"

  #list items
  datesinlist = true
  authorsinlist = false

  #footer items
  nextprev = true
  taglist = true
  showrss = true